Class = require("Ripstal.Class")
Utils = require("Ripstal.utils")
Cutscene = require("Ripstal.cutscene")
BattleCutscene = require("Ripstal.battlecutscene")
Object = require("Ripstal.Object")
Bullet = require("Ripstal.Bullet")
Registry = require("Ripstal.Registry")
Timer = require("Ripstal.Timer")
require("Ripstal.ScriptScopes.main")